name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Scarb
        run: |
          curl -L https://github.com/software-mansion/scarb/releases/download/v0.7.0/scarb-v0.7.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv scarb /usr/local/bin/

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Build contracts
        run: |
          scarb build

      - name: Run tests
        run: |
          scarb test
