name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Scarb
        run: |
          curl -L https://github.com/software-mansion/scarb/releases/download/v0.7.0/scarb-v0.7.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ls -l  # Debug: List files after extraction to find the scarb binary
          sudo mv scarb-v0.7.0-x86_64-unknown-linux-gnu/scarb /usr/local/bin/
          sudo chmod +x /usr/local/bin/scarb
          scarb --version  # Ensure it installed correctly

      - name: Build contracts
        run: |
          scarb build

      - name: Run tests
        run: |
          scarb test
