name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.1"
      - uses: foundry-rs/setup-snfoundry@v1
        with:
          snfoundry-version: "0.32.0"  # Replace with the desired version
      - run: scarb fmt --check
      - run: scarb test
