name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "latest" 

      - name: Install snforge
        run: |
          curl -L https://github.com/software-mansion/snforge/releases/download/v0.2.0/snforge-v0.2.0-linux-x86_64.tar.gz | tar xz
          sudo mv snforge /usr/local/bin/
          sudo chmod +x /usr/local/bin/snforge

      - name: Run Scarb Build
        run: |
          scarb build

      - name: Run Scarb Tests
        run: |
          scarb test
